## TensorFlow Fundamentals Exercises

In [ ]:
import tensorflow as tf
tf.__version__

### Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [ ]:
scalar = tf.constant(10)
scalar, scalar.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=10>, 0)

In [ ]:
vector = tf.constant([10, 20, 30])
vector, vector.ndim

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30], dtype=int32)>,
 1)

In [ ]:
matrix = tf.constant([[10, 20], [20, 30], [30, 40]])
matrix, matrix.ndim

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10, 20],
        [20, 30],
        [30, 40]], dtype=int32)>,
 2)

### Find the shape, rank and size of the tensors you created in 1.


In [ ]:
tf.shape(scalar), tf.rank(scalar), tf.size(scalar)

(<tf.Tensor: shape=(0,), dtype=int32, numpy=array([], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [ ]:
tf.shape(vector), tf.rank(vector), tf.size(vector)

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>)

In [ ]:
tf.shape(matrix), tf.rank(matrix), tf.size(matrix)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=6>)

### Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [ ]:
random_tensor1 = (tf.random.uniform(shape = [5, 300], minval=0, maxval=1))
random_tensor2 = (tf.random.uniform(shape = [5, 300], minval=0, maxval=1))

In [ ]:
random_tensor1, random_tensor2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.55451727, 0.6384561 , 0.46938038, ..., 0.26989233, 0.4495077 ,
         0.7879046 ],
        [0.32669437, 0.6589227 , 0.21281207, ..., 0.48792648, 0.34462917,
         0.93857455],
        [0.9098244 , 0.21872842, 0.29917526, ..., 0.7055981 , 0.35749197,
         0.42468834],
        [0.81573164, 0.6425661 , 0.10810184, ..., 0.45176804, 0.40509188,
         0.16038835],
        [0.7784375 , 0.93037117, 0.8185934 , ..., 0.21573067, 0.54595745,
         0.11508071]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.61582375, 0.8879032 , 0.32362258, ..., 0.51914084, 0.3464687 ,
         0.703516  ],
        [0.2939211 , 0.1373837 , 0.96810913, ..., 0.47529352, 0.16518223,
         0.31362438],
        [0.84832084, 0.8403758 , 0.10939491, ..., 0.80623424, 0.66880274,
         0.9721596 ],
        [0.87573016, 0.39885402, 0.40293574, ..., 0.40396988, 0.9657265 ,
         0.9048463 ],
        [0.70405

### Multiply the two tensors you created in 3 using matrix multiplication.


In [ ]:
tf.multiply(random_tensor1, random_tensor2)

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.3414849 , 0.5668872 , 0.1519021 , ..., 0.14011213, 0.15574035,
        0.5543035 ],
       [0.09602237, 0.09052523, 0.2060253 , ..., 0.23190829, 0.05692662,
        0.29435986],
       [0.771823  , 0.18381406, 0.03272825, ..., 0.56887734, 0.2390916 ,
        0.41286486],
       [0.7143608 , 0.25629008, 0.0435581 , ..., 0.18250069, 0.39120796,
        0.1451268 ],
       [0.54805964, 0.76412207, 0.4566326 , ..., 0.21438162, 0.03407066,
        0.0655309 ]], dtype=float32)>

### Multiply the two tensors you created in 3 using dot product.


In [ ]:
tf.matmul(random_tensor1, tf.transpose(random_tensor2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.72993 , 73.945114, 76.12347 , 71.78844 , 73.69748 ],
       [74.87637 , 75.68959 , 75.00468 , 71.65782 , 77.222   ],
       [71.48894 , 72.18129 , 70.34221 , 68.7372  , 72.88876 ],
       [71.60243 , 71.3188  , 70.77015 , 68.69643 , 73.78714 ],
       [79.011116, 77.23245 , 75.57366 , 70.72732 , 74.91632 ]],
      dtype=float32)>

### Create a tensor with random values between 0 and 1 with shape [224, 224, 3].


In [ ]:
random_val = tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1)
random_val

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[2.6177049e-02, 4.3350232e-01, 5.3156149e-01],
        [6.2664318e-01, 5.9968030e-01, 2.3002744e-02],
        [8.0309319e-01, 6.3837051e-02, 1.5879643e-01],
        ...,
        [2.6351905e-01, 4.3552577e-01, 2.2698915e-01],
        [7.0905185e-01, 9.7654259e-01, 2.0450521e-01],
        [4.3149829e-01, 5.6950235e-01, 3.0482590e-01]],

       [[1.3896155e-01, 1.9372201e-01, 2.9997492e-01],
        [9.1130912e-01, 7.6567852e-01, 9.7878265e-01],
        [5.7622802e-01, 9.7333086e-01, 8.8605165e-02],
        ...,
        [1.5731752e-01, 9.2043424e-01, 4.4410050e-01],
        [1.7267168e-01, 1.3768601e-01, 3.8259268e-01],
        [9.5152497e-01, 4.3960953e-01, 7.8094006e-04]],

       [[9.6418381e-02, 3.4175813e-01, 8.5101283e-01],
        [7.1648645e-01, 3.0520689e-01, 7.2785616e-02],
        [1.9891262e-02, 5.7351863e-01, 1.9453025e-01],
        ...,
        [2.0735359e-01, 6.7894793e-01, 4.9048328e-01],
        [5.4373658e-01

In [ ]:
tf.reduce_min(random_val, axis=0)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[1.03225708e-02, 2.86829472e-03, 1.10411644e-03],
       [4.22930717e-03, 4.21285629e-04, 3.23653221e-04],
       [2.89285183e-03, 8.07166100e-04, 6.28304482e-03],
       [1.98209286e-02, 5.19728661e-03, 2.38823891e-03],
       [3.61061096e-03, 1.72817707e-03, 9.94563103e-04],
       [3.08787823e-03, 2.38955021e-03, 1.76346302e-03],
       [8.30292702e-04, 5.84483147e-04, 8.63075256e-05],
       [3.55827808e-03, 1.24126673e-02, 5.11062145e-03],
       [2.60055065e-03, 3.43036652e-03, 2.24566460e-03],
       [6.21914864e-04, 5.64837456e-03, 6.16300106e-03],
       [4.06825542e-03, 5.55157661e-03, 4.67014313e-03],
       [3.85522842e-04, 2.20465660e-03, 2.88832188e-03],
       [8.47935677e-04, 1.28269196e-04, 3.56900692e-03],
       [4.83953953e-03, 6.64579868e-03, 1.08778477e-03],
       [5.78880310e-04, 2.00045109e-03, 5.00607491e-03],
       [2.47514248e-03, 7.91668892e-04, 1.90937519e-03],
       [3.85522842e-04, 1.14074945e-02

In [ ]:
tf.reduce_max(random_val, axis = 0)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[0.9998952 , 0.99718404, 0.98676336],
       [0.99980295, 0.998317  , 0.99753773],
       [0.9998652 , 0.9995959 , 0.9868499 ],
       [0.99767196, 0.9957211 , 0.99931407],
       [0.9996979 , 0.99526453, 0.9997643 ],
       [0.9947907 , 0.9909705 , 0.99343455],
       [0.9896432 , 0.99688935, 0.9952135 ],
       [0.9987316 , 0.9983791 , 0.98868716],
       [0.99888504, 0.99903846, 0.995497  ],
       [0.99563575, 0.99932516, 0.99868643],
       [0.99968946, 0.99985874, 0.98990786],
       [0.9996593 , 0.9958868 , 0.99576604],
       [0.9886888 , 0.99902546, 0.997015  ],
       [0.9995674 , 0.9945704 , 0.9918021 ],
       [0.9965198 , 0.9996233 , 0.9890946 ],
       [0.99571085, 0.9989135 , 0.99960876],
       [0.99083793, 0.98912346, 0.99927557],
       [0.99923885, 0.9975804 , 0.99852884],
       [0.9987687 , 0.99976814, 0.98876584],
       [0.99716854, 0.99910367, 0.9989761 ],
       [0.9991361 , 0.99388003, 0.99642277],
     

### Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [ ]:
random_tensor = tf.random.uniform(shape=[1, 224, 224, 3])
random_tensor, random_tensor.shape

(<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
 array([[[[0.8609787 , 0.03678107, 0.342363  ],
          [0.8629923 , 0.7936301 , 0.9943973 ],
          [0.71474946, 0.91908693, 0.05738306],
          ...,
          [0.64362645, 0.35029984, 0.36555338],
          [0.03724051, 0.45079935, 0.5102205 ],
          [0.7066957 , 0.20152354, 0.19660378]],
 
         [[0.56666005, 0.42598617, 0.5459957 ],
          [0.16943991, 0.40359616, 0.19598651],
          [0.0033704 , 0.8164679 , 0.20837677],
          ...,
          [0.75424576, 0.2245946 , 0.30476296],
          [0.27675092, 0.54379904, 0.23706424],
          [0.01653385, 0.11966121, 0.7157091 ]],
 
         [[0.8626224 , 0.39744794, 0.48749173],
          [0.899191  , 0.5513272 , 0.8930917 ],
          [0.64977217, 0.95285773, 0.535434  ],
          ...,
          [0.21723127, 0.0937295 , 0.5003027 ],
          [0.55821824, 0.20919836, 0.31305003],
          [0.86447394, 0.21763897, 0.91467917]],
 
         ...,
 
       

In [ ]:
tf.squeeze(random_tensor)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.8609787 , 0.03678107, 0.342363  ],
        [0.8629923 , 0.7936301 , 0.9943973 ],
        [0.71474946, 0.91908693, 0.05738306],
        ...,
        [0.64362645, 0.35029984, 0.36555338],
        [0.03724051, 0.45079935, 0.5102205 ],
        [0.7066957 , 0.20152354, 0.19660378]],

       [[0.56666005, 0.42598617, 0.5459957 ],
        [0.16943991, 0.40359616, 0.19598651],
        [0.0033704 , 0.8164679 , 0.20837677],
        ...,
        [0.75424576, 0.2245946 , 0.30476296],
        [0.27675092, 0.54379904, 0.23706424],
        [0.01653385, 0.11966121, 0.7157091 ]],

       [[0.8626224 , 0.39744794, 0.48749173],
        [0.899191  , 0.5513272 , 0.8930917 ],
        [0.64977217, 0.95285773, 0.535434  ],
        ...,
        [0.21723127, 0.0937295 , 0.5003027 ],
        [0.55821824, 0.20919836, 0.31305003],
        [0.86447394, 0.21763897, 0.91467917]],

       ...,

       [[0.27650142, 0.7934798 , 0.3554176 ],
        [0.38

### Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.


In [ ]:
ten_shape = tf.constant([1, 2, 3, 4, 5, 20, 7, 8, 9, 10])
ten_shape

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5, 20,  7,  8,  9, 10], dtype=int32)>

In [ ]:
tf.argmax(ten_shape)

<tf.Tensor: shape=(), dtype=int64, numpy=5>

### One-hot encode the tensor you created in 9.

In [53]:
tf.one_hot(ten_shape, depth = 10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>